name: Test Push
on:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "${{ github.event.head_commit.message }}"
  run-if:
    if: contains(github.event.head_commit.message, '[RELEASE]')
    runs-on: ubuntu-latest
    steps:
      - name: contains
        run: |
          echo "contains"
