name: Test Push
on:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "${{ github.ref_name }}"
          echo "${{ github.event.ref }}"
          echo "${{ github.event.base_ref }}"
          echo "${{ github.event.commits }}"
          echo "${{ github.event.pull_request }}"
          echo "${{ github.event.pull_request.title }}"
