name: Test Push
on:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "${{ github.ref_name }}"
          echo "${{ github.event.ref }}"
          echo "$EVENT"
        env:
          EVENT: ${{ github.event }}
